version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - ./etc/initdb:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user

volumes:
  db_data: {}